package com.knowledge.dto;

import cn.afterturn.easypoi.excel.annotation.Excel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class DiagnosisResultDto {
    @Excel(name = "序号")
    private String serialNo;
    @Excel(name = "术语编号")
    private String termNo;
    @Excel(name = "术语名称")
    private String termName;

    @Excel(name = "别名名称")
    private String aliasName;
    @Excel(name = "别名内容")
    private String aliasContent;
    @Excel(name = "别名来源")
    private String aliasSource;
    @Excel(name = "类别名称")
    private String categoryName;
    @Excel(name = "类别内容")
    private String categoryContent;
    @Excel(name = "类别来源")
    private String categorySource;
    @Excel(name = "罕见病名称")
    private String rareDiseaseName;
    @Excel(name = "罕见病内容")
    private String rareDiseaseContent;
    @Excel(name = "罕见病来源")
    private String rareDiseaseSource;
    @Excel(name = "合并症名称")
    private String complicationName;
    @Excel(name = "合并症内容")
    private String complicationContent;
    @Excel(name = "合并症来源")
    private String complicationSource;
    @Excel(name = "部位名称")
    private String positionName;
    @Excel(name = "部位内容")
    private String positionContent;
    @Excel(name = "部位来源")
    private String positionSource;
    @Excel(name = "专有年龄值")
    private String proprietaryAgeValue;
    @Excel(name = "专有年龄单位")
    private String proprietaryAgeUnit;
    @Excel(name = "专有年龄内容")
    private String proprietaryAgeContent;
    @Excel(name = "专有年龄来源")
    private String proprietaryAgeSource;
    @Excel(name = "专有性别名称")
    private String proprietaryGenderName;
    @Excel(name = "专有性别内容")
    private String proprietaryGenderContent;
    @Excel(name = "专有性别来源")
    private String proprietaryGenderSource;
    @Excel(name = "专有病史名称")
    private String medicalHistoryName;
    @Excel(name = "专有病史内容")
    private String medicalHistoryContent;
    @Excel(name = "专有病史来源")
    private String medicalHistorySource;
    @Excel(name = "年龄因素值")
    private String ageFactorValue;
    @Excel(name = "年龄因素单位")
    private String ageFactorUnit;
    @Excel(name = "年龄因素级别")
    private String ageFactorLevel;
    @Excel(name = "年龄因素内容")
    private String ageFactorContent;
    @Excel(name = "年龄因素来源")
    private String ageFactorSource;
    @Excel(name = "性别因素单位")
    private String genderFactorValue;
    @Excel(name = "年性别因素级别")
    private String genderFactorLevel;
    @Excel(name = "性别因素内容")
    private String genderFactorContent;
    @Excel(name = "性别因素来源")
    private String genderFactorSource;
    @Excel(name = "鉴别诊断疾病")
    private String identifyDisease;
    @Excel(name = "鉴别诊断症状")
    private String identifySymptom;
    @Excel(name = "鉴别诊断内容")
    private String identifyContent;
    @Excel(name = "鉴别诊断来源")
    private String identifySource;

    @Excel(name = "阳性症状名称")
    private String positiveSymptomName;
    @Excel(name = "阳性症状证据内容")
    private String positiveSymptomContent;
    @Excel(name = "阳性症状证据来源")
    private String positiveSymptomSource;
    @Excel(name = "阳性体征A名称")
    private String positiveSignAName;
    @Excel(name = "阳性体征A结果")
    private String positiveSignAResult;
    @Excel(name = "阳性体征A证据内容")
    private String positiveSignAContent;
    @Excel(name = "阳性体征A证据来源")
    private String positiveSignASource;
    @Excel(name = "阳性体征B名称")
    private String positiveSignBName;
    @Excel(name = "阳性体征B值")
    private String positiveSignBValue;
    @Excel(name = "阳性体征B单位")
    private String positiveSignBUnit;
    @Excel(name = "阳性体征B证据内容")
    private String positiveSignBContent;
    @Excel(name = "阳性体征B证据来源")
    private String positiveSignBSource;
    @Excel(name = "阳性检验A名称")
    private String positiveExamineAName;
    @Excel(name = "阳性检验A指标")
    private String positiveExamineATarget;
    @Excel(name = "阳性检验A结果")
    private String positiveExamineAResult;
    @Excel(name = "阳性检验A证据内容")
    private String positiveExamineContent;
    @Excel(name = "阳性检验A证据来源")
    private String positiveExamineASource;
    @Excel(name = "阳性检验B名称")
    private String positiveExamineBName;
    @Excel(name = "阳性检验A指标")
    private String positiveExamineBTarget;
    @Excel(name = "阳性检验B值")
    private String positiveExamineBValue;
    @Excel(name = "阳性检验B单位")
    private String positiveExamineBUnit;
    @Excel(name = "阳性检验B证据内容")
    private String positiveExamineBContent;
    @Excel(name = "阳性检验B证据来源")
    private String positiveExamineBSource;
    @Excel(name = "阳性检查A名称")
    private String positiveInspectAName;
    @Excel(name = "阳性检查A结果")
    private String positiveInspectAResult;
    @Excel(name = "阳性检查A证据内容")
    private String positiveInspectAContent;
    @Excel(name = "阳性检查A证据来源")
    private String positiveInspectASource;
    @Excel(name = "阳性检查B名称")
    private String positiveInspectBName;
    @Excel(name = "阳性检查B值")
    private String positiveInspectBValue;
    @Excel(name = "阳性检查B单位")
    private String positiveInspectBUnit;
    @Excel(name = "阳性检查B证据内容")
    private String positiveInspectBContent;
    @Excel(name = "阳性检查B证据来源")
    private String positiveInspectBSource;

    @Excel(name = "阴性症状名称")
    private String negativeSymptomName;
    @Excel(name = "阴性症状证据内容")
    private String negativeSymptomContent;
    @Excel(name = "阴性症状证据来源")
    private String negativeSymptomSource;
    @Excel(name = "阴性体征A名称")
    private String negativeSignAName;
    @Excel(name = "阴性体征A结果")
    private String negativeSignAResult;
    @Excel(name = "阴性体征A证据内容")
    private String negativeSignAContent;
    @Excel(name = "阴性体征A证据来源")
    private String negativeSignASource;
    @Excel(name = "阴性体征B名称")
    private String negativeSignBName;
    @Excel(name = "阴性体征B值")
    private String negativeSignBValue;
    @Excel(name = "阴性体征B单位")
    private String negativeSignBUnit;
    @Excel(name = "阴性体征B证据内容")
    private String negativeSignBContent;
    @Excel(name = "阴性体征B证据来源")
    private String negativeSignBSource;
    @Excel(name = "阴性检验A名称")
    private String negativeExamineAName;
    @Excel(name = "阴性检验A指标")
    private String negativeExamineATarget;
    @Excel(name = "阴性检验A结果")
    private String negativeExamineAResult;
    @Excel(name = "阴性检验A证据内容")
    private String negativeExamineContent;
    @Excel(name = "阴性检验A证据来源")
    private String negativeExamineASource;
    @Excel(name = "阴性检验B名称")
    private String negativeExamineBName;
    @Excel(name = "阴性检验A指标")
    private String negativeExamineBTarget;
    @Excel(name = "阴性检验B值")
    private String negativeExamineBValue;
    @Excel(name = "阴性检验B单位")
    private String negativeExamineBUnit;
    @Excel(name = "阴性检验B证据内容")
    private String negativeExamineBContent;
    @Excel(name = "阴性检验B证据来源")
    private String negativeExamineBSource;
    @Excel(name = "阴性检查A名称")
    private String negativeInspectAName;
    @Excel(name = "阴性检查A结果")
    private String negativeInspectAResult;
    @Excel(name = "阴性检查A证据内容")
    private String negativeInspectAContent;
    @Excel(name = "阴性检查A证据来源")
    private String negativeInspectASource;
    @Excel(name = "阴性检查B名称")
    private String negativeInspectBName;
    @Excel(name = "阴性检查B值")
    private String negativeInspectBValue;
    @Excel(name = "阴性检查B单位")
    private String negativeInspectBUnit;
    @Excel(name = "阴性检查B证据内容")
    private String negativeInspectBContent;
    @Excel(name = "阴性检查B证据来源")
    private String negativeInspectBSource;

    @Excel(name = "关联手术名称")
    private String associatedSurgeryName;
    @Excel(name = "关联手术内容")
    private String associatedSurgeryContent;
    @Excel(name = "关联手术来源")
    private String associatedSurgerySource;
    @Excel(name = "关联临床路径名称")
    private String clinicalPathwayName;
    @Excel(name = "关联临床路径内容")
    private String clinicalPathwayContent;
    @Excel(name = "关联临床路径来源")
    private String clinicalPathwaySource;
    @Excel(name = "关联评估量表名称")
    private String assessmentScaleName;
    @Excel(name = "关联评估量表内容")
    private String assessmentScaleContent;
    @Excel(name = "关联评估量表来源")
    private String assessmentScaleSource;
    @Excel(name = "添加人员")
    private String createPeople;
    @Excel(name = "添加时间")
    private String createTime;
    @Excel(name = "审核人员")
    private String reviewer;

    /*@Excel(name = "临时文档类型")
    private String tempFileType;
    @Excel(name = "临时术语名称")
    private String tempTermName;
    @Excel(name = "临时序号")
    private int tempSerialNo;*/
}
